apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flowforge

resources:
  - ../../base
  - hpa-backend.yaml
  - hpa-frontend.yaml
  - pdb-backend.yaml
  - pdb-frontend.yaml
  - ingress.yaml

patches:
  - path: resource-limits.yaml
  - path: backend-config-patch.yaml
