global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "flowforge-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]
        labels:
          service: "backend"

  - job_name: "toxiproxy"
    metrics_path: /metrics
    static_configs:
      - targets: ["toxiproxy:8474"]
        labels:
          service: "toxiproxy"
