apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flowforge

resources:
  - namespace.yaml
  # Infrastructure
  - infra/redpanda.yaml
  - infra/clickhouse.yaml
  - infra/materialize.yaml
  - infra/redis.yaml
  - infra/postgres.yaml
  # Pipeline
  - pipeline/data-generator.yaml
  - pipeline/bytewax.yaml
  - pipeline/airflow.yaml
  - pipeline/init-materialize-job.yaml
  # Application
  - app/backend.yaml
  - app/frontend.yaml
